name: CI

on:
  push:
    branches:
      - '!*'
      - '!main'
  pull_request:
    branches:
      - '!*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test:coverage

      - name: Upload coverage report (v3)
        if: matrix.node-version < 20
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Upload coverage report (v4)
        if: matrix.node-version >= 20
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
